[font]
size = 12.0

[font.bold]
family = "hack"

[font.bold_italic]
family = "hack"

[font.italic]
family = "hack"

[font.normal]
family = "hack"

[window]
opacity = 0.95

[window.padding]
x = 10
y = 10
