[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font Mono"

[font.bold_italic]
family = "Hack Nerd Font Mono"

[font.italic]
family = "Hack Nerd Font Mono"

[font.normal]
family = "Hack Nerd Font Mono"

[window]
opacity = 0.90
blur = true
decorations = "None"
startup_mode = "Maximized"

[window.padding]
x = 12
y = 20
